services:
  redis:
    image: redis/redis-stack-server:6.2.6-v15
    volumes:
      - redis-data:/data
    restart: always
    ports:
      - "6378:6379"
    networks: 
      - net
    
volumes:
  redis-data:

networks:
  net: