services:
  redis:
    image: redis/redis-stack-server:6.2.6-v15
    volumes:
      - redis-data:/data
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks: 
      - net

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: users_salary
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 3s
      retries: 3
    networks: 
      - net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: salary_backend
    ports:
      - '8000:8000'
    restart: on-failure
    networks: 
      - net
    
    
volumes:
  redis-data:
  pgdata:

networks:
  net: